services:
  - type: web
    name: orbix
    runtime: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENC_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
